### PR TITLE
MNT: rerender

### LINKED ISSUE #8: @conda-forge-admin, please rerender
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #8.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #8

### CODE REVIEW

**Comment by BastianZim** [comment]
@mfeurer Hey, quick question: I tried to rerender the package because the upload failed but it's also failing here.

Reason seems to be that smack somewhere checks the versions of installed packages but is unable to do so for emcee. I first thought that it was a problem with emcee but if I run `emcee.__version__` locally I get `3.1.1` so I don't think that this is the culprit. Do you have any idea where this could come from?

Logs: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=451347&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=501

**Comment by mfeurer** [comment]
No, sorry. CC @renesass as current maintainer of SMAC3.

**Comment by renesass** [comment]
Hey, in the next version 1.2 we replaced LooseVersion with packaging.version.Version. This might hopefully solve the issue.

**Comment by BastianZim** [comment]
Ok thanks for the feedback. Do you have an ETA for that as it’s currently blocking the release here?

I can also apply a patch here if you have the code already.

**Comment by renesass** [comment]
Can you test if this file solves the issue?
https://github.com/automl/SMAC3/blob/fba8d05c66a7efa8925679f97572285f9708b835/smac/utils/dependencies.py

Version 1.2 is basically ready. We're only fixing tests and after the review phase we will publish it. Should take less than one week, I guess.

**Comment by BastianZim** [comment]
I applied your commit as a patch but it's still not working, unfortunately. Would it be possible to disable this check using an env variable or something since the conda solver should already make sure that the version is correct?

**Comment by BastianZim** [comment]
@renesass Do you have any other idea how we can fix this?

**Comment by renesass** [comment]
Is it only because of emcee? Can you remove it and see if it works without?

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
Emcee seems to be required so I don't think I can remove it. 

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=459712&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

**Comment by BastianZim** [comment]
@renesass I think I tracked down the error:

Whether `pkg_resources.get_distribution` can find a version or not is apparently dependent on how the package was built (Ref: https://github.com/googleapis/python-api-core/issues/27).

Your [fallback](https://github.com/automl/SMAC3/blob/863e4290054847ba2688521b8cc2e44c15a1493a/smac/utils/dependencies.py#L46) to `emcee.__version__` seems to be the correct approach, the problem is that the version reported is not `None` it's always `0.0.0` so `emcee.__version__` is never reached.
I have verified that `emcee.__version__` gives out `3.1.1` so that would be the best approach.

I'm not sure what your coding principle are but could SMAC also fallback to `emcee.__version__` if the reported version is `0.0.0` or is that too much of a workaround?

In that case we could also include it as a patch here.

**Comment by BastianZim** [comment]
@renesass Gentle ping here, if you have a sec.

**Comment by renesass** [comment]
Hey,

I'm really sorry for my late response (was to that time in holiday and then it went off my head).
I posted an update here: https://github.com/automl/SMAC3/pull/835

Would that fix our issue here?

**Comment by renesass** [comment]
I will initiate the procedure to get this pushed.
Thanks for your work :)

**Comment by BastianZim** [comment]
Thank you! :)

No that's fine, doesn't change anything.

**Comment by renesass** [comment]
Hey,

we just published the new version 1.3.2.
I hope that solves our problems here. :)

**Comment by BastianZim** [comment]
Awesome, thank you! The bot should make a PR for this in the next couple of hours.

**Pull request closed without merging**
